# SPDX-FileCopyrightText: 2025 Legiayayana
#
# SPDX-License-Identifier: EUPL-1.2

edition = "2024"
max_width = 120
hard_tabs = true

reorder_imports = true
reorder_modules = true
normalize_comments = true
normalize_doc_attributes = true
newline_style = "Unix"
hex_literal_case = "Lower"
group_imports = "StdExternalCrate"
