[package]
name = "akizuki_cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
colog = "1.3.0"
colored = "2.2.0"
env_logger = "0.11.8"
log = "0.4.27"