<!--
SPDX-FileCopyrightText: 2026 Neptuwunium

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Library\Neptune\Pluto.SourceGen\Pluto.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
		<ProjectReference Include="..\Library\Neptune\Pluto\Pluto.csproj"/>
		<ProjectReference Include="..\Library\Ferment\Ferment\Ferment.csproj"/>
		<ProjectReference Include="..\Library\Neptune\Ceres\Ceres.csproj"/>
		<ProjectReference Include="..\Library\Neptune\Triton\Triton.csproj"/>
		<ProjectReference Include="..\Library\Neptune\Charon\Charon.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Serilog" Version="4.3.1"/>
		<PackageReference Include="Silk.NET.Maths" Version="2.23.0"/>
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>Akizuki.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
