# SPDX-FileCopyrightText: 2025 Legiayayana
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "akizuki"
version = "0.1.0"
edition = "2024"

[dependencies]
cantrip = "0.4.0"
cityhash-rs = "1.0.1"
crc = "3.2.1"
flate2 = "1.0"
glam = "0.30.1"
log = "0.4.27"
murmur3 = "0.5.2"
xml = "0.8.20"

# geometry
gltf = { version = "1.4.1", features = ["extensions", "extras", "names", "KHR_texture_transform"], optional = true }

# texture
bcdec_rs = { version = "0.2.0", optional = true }
png = { version = "0.17.16", optional = true }
tiff = { version = "0.9.1", optional = true }

[features]
geometry = ["gltf"]
texture = ["bcdec_rs", "png", "tiff"]
art = ["texture", "geometry"]