# SPDX-FileCopyrightText: 2025 Legiayayana
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "akizuki"
version = "0.1.0"
edition = "2024"

[dependencies]
akizuki_common = { path = "../akizuki_common" }
akizuki_macro = { path = "../akizuki_macro" }

binrw = "0"
cityhasher = "0"
colored = "3"
crc = "3"
dlopen2 = "0"
flate2 = "1"
four-char-code = "2"
log = "0"
memmap2 = "0"
once_cell = "1"
thiserror = "2"

# locale
gettext = { version = "0", optional = true }

# data
glam = { version = "0", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
serde-pickle = { version = "1", optional = true }
serde-xml-rs = { version = "0", optional = true }
serde_with = { version = "3", optional = true }

# geometry
gltf = { version = "1", features = ["extensions", "extras", "names", "KHR_texture_transform"], optional = true }
half = { version = "2", optional = true }
meshopt = { version = "0", optional = true }
bytemuck = { version = "1", optional = true }

# texture
image_dds = { version = "0", optional = true }
image = { version = "0", optional = true }

[features]
geometry = ["glam", "gltf", "half", "meshopt", "bytemuck"]
texture = ["image_dds", "image"]
locale = ["gettext"]
data = ["glam", "serde", "serde-pickle", "serde-xml-rs"]
serialize = ["serde", "serde_with", "glam/serde"]

art = ["texture", "geometry"]
default = ["art", "data", "locale", "serialize"]
