# SPDX-FileCopyrightText: 2025 Legiayayana
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "akizuki-unpack"
version = "0.1.0"
edition = "2024"
authors = ["Legiayayana"]
license = "EUPL-1.2"

[dependencies]
akizuki = { path = "../../akizuki" }
akizuki_cli = { path = "../../akizuki_cli" }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = "1"
serde_json = "1"
log = "0"
