# SPDX-FileCopyrightText: 2025 Legiayayana
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "akizuki-viewer"
version = "0.1.0"
edition = "2024"
authors = ["Legiayayana"]
license = "EUPL-1.2"

[dependencies]
akizuki = { path = "../../akizuki" }
akizuki_cli = { path = "../../akizuki_cli" }

bevy = "0.16"
bevy_asset = "0.16"
bevy_panorbit_camera = "0.27"
clap = { version = "4", features = ["derive"] }
colog = "1"
colored = "3"
env_logger = "0"
log = "0"
once_cell = "1.21.3"