# SPDX-FileCopyrightText: 2025 Legiayayana
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "akizuki-viewer"
version = "0.1.0"
edition = "2024"
authors = ["Legiayayana"]
license = "EUPL-1.2"

[dependencies]
akizuki = { path = "../../akizuki" }
akizuki_cli = { path = "../../akizuki_cli" }

bytemuck = "1"
log = "0"
pollster = "0"
wgpu = "25"
winit = "0"
imgui = "0"
imgui-wgpu = "0"
imgui-winit-support = "0"
